---
- name: Copy *.md files to deploy home on DB hosts
  hosts: db
  become: true

  tasks:
    - name: Copy all local *.md files to /home/deploy/
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /home/deploy/
        owner: deploy
        group: deploy
        mode: '0644'
      with_fileglob:
        - "files/*.md"
