---
- name: Clean up old passwordless sudo rules
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Disable old cloud-init sudo rule
      ansible.builtin.file:
        path: /etc/sudoers.d/90-cloud-init-users
        state: absent

    - name: Disable old deploy sudo rule
      ansible.builtin.file:
        path: /etc/sudoers.d/deploy
        state: absent

    - name: Ensure secure sudo rule is in place
      ansible.builtin.copy:
        dest: /etc/sudoers.d/99-deploy
        owner: root
        group: root
        mode: '0440'
        content: |
          deploy ALL=(ALL) ALL
        validate: 'visudo -cf %s'

