---
- name: Ensure nginx is installed
  ansible.builtin.package:
    name: nginx
    state: present

- name: Copy nginx configuration from template
  ansible.builtin.template:
    src: templates/example.internal.conf.j2
    dest: /etc/nginx/conf.d/example.internal.conf

- name: Ensure nginx is started and enabled
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

