#Webserver Tasks
---
- name: Set up self-signed certificates for HTTPS
  hosts: webserver
  become: true
  tasks:
    - name: Ensure the /etc/pki/nginx directory exists
      ansible.builtin.file:
        path: /etc/pki/nginx
        state: directory
        mode: "0755"
        owner: root

    - name: Ensure we have a /etc/pkig/nginx/private directory
      ansible.builtin.file:
        path: /etc/pki/nginx/private
        state: directory
        mode: "0700"
        owner: root

    - name: Ensure we have software installed
      ansible.builtin.package:
        name: python3-cryptography
        state: present

    - name: Ensure we have a private key for our certificate
      community.crypto.openssl_privatekey:
        path: /etc/pki/nginx/private/server.key

    - name: Create a self-signed certificate
      community.crypto.x509_certificate:
        path: /etc/pki/nginx/server.crt
        privatekey_path: /etc/pki/nginx/private/server.key
        provider: selfsigned




- name: Ensure nginx is installed
  ansible.builtin.package:
    name: nginx
    state: present

- name: Deploy https.conf
  ansible.builtin.copy:
    src: https.conf              # ligger i roles/webserver/files/
    dest: /etc/nginx/conf.d/https.conf
    owner: root
    group: root
    mode: '0644'
  notify: reload nginx

- name: Deploy vhost template
  ansible.builtin.template:
    src: example.internal.conf.j2 # ligger i roles/webserver/templates/
    dest: /etc/nginx/conf.d/example.internal.conf
    owner: root
    group: root
    mode: '0644'
  notify: reload nginx

- name: Ensure web root exists
  ansible.builtin.file:
    path: /var/www/example.internal/html
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Install index.html
  ansible.builtin.copy:
    src: index.html              # roles/webserver/files/
    dest: /var/www/example.internal/html/index.html
    owner: root
    group: root
    mode: '0644'

- name: Ensure nginx started & enabled
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
