---
- name: Ensure MariaDB-server is installed
  ansible.builtin.package:
    name: mariadb-server
    state: present

- name: Ensure python3-PyMySQL is installed
  ansible.builtin.package:
    name: python3-PyMySQL
    state: present

- name: Ensure MariaDB service is enabled and started
  ansible.builtin.service:
    name: mariadb
    enabled: true
    state: started

- name: Create database webappdb
  community.mysql.mysql_db:
    name: webappdb
    state: present
    login_unix_socket: /var/lib/mysql/mysql.sock

- name: Create MariaDB user
  community.mysql.mysql_user:
    name: webappuser
    password: '{{ webappdb_password }}'
    priv: webappdb.*:ALL
    login_unix_socket: /var/lib/mysql/mysql.sock

